// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRvZ58h02NJSzeMVZn8GNJcMntw0GBvhE',
    appId: '1:153155833165:web:70d64b0a98bd45108f7b04',
    messagingSenderId: '153155833165',
    projectId: 'clasemoviles-804f9',
    authDomain: 'clasemoviles-804f9.firebaseapp.com',
    storageBucket: 'clasemoviles-804f9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdK47g6eL3gUatDp0bWI2vofVNZsNvGfI',
    appId: '1:153155833165:android:858186596a8f626b8f7b04',
    messagingSenderId: '153155833165',
    projectId: 'clasemoviles-804f9',
    storageBucket: 'clasemoviles-804f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlRKdxvNAkY2ZNfA5RSY3JVxUBcpZNDqo',
    appId: '1:153155833165:ios:23e4f3870dd004af8f7b04',
    messagingSenderId: '153155833165',
    projectId: 'clasemoviles-804f9',
    storageBucket: 'clasemoviles-804f9.appspot.com',
    iosBundleId: 'com.example.chatFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlRKdxvNAkY2ZNfA5RSY3JVxUBcpZNDqo',
    appId: '1:153155833165:ios:5775428e7c07ce8c8f7b04',
    messagingSenderId: '153155833165',
    projectId: 'clasemoviles-804f9',
    storageBucket: 'clasemoviles-804f9.appspot.com',
    iosBundleId: 'com.example.chatFlutter.RunnerTests',
  );
}
